### ISSUE TITLE
RFDiffusion Partial Diffusion Error: Mismatched Contig Length

### ISSUE THREAD

**Issue by mavericb** [RosettaCommons/RFdiffusion#266]
## Description
I'm encountering an error when running RFDiffusion for partial diffusion. The error suggests a mismatch between the length of the input PDB and the length of the contig string.

## Simplified Code
```python
import subprocess

def run_rfdiffusion_partial():
    input_pdb = "/path/to/input.pdb"
    output_dir = "/path/to/output"
    
    command = [
        "docker", "run", "--rm", "--gpus", "all",
        "-v", "/path/to/models:/models",
        "-v", f"{input_pdb}:{input_pdb}",
        "-v", f"{output_dir}:{output_dir}",
        "rfdiffusion",
        f"inference.output_prefix={output_dir}/output",
        f"inference.model_directory_path=/models",
        f"inference.input_pdb={input_pdb}",
        "contigmap.contigs=[222-222/0 10]",
        "diffuser.partial_T=1",
        "contigmap.provide_seq=[172-205]"
    ]
    
    process = subprocess.run(command, capture_output=True, text=True)
    if process.returncode != 0:
        print(f"Error: {process.stderr}")

run_rfdiffusion_partial()
```

## Error Message
```
implied by the contig string for partial diffusion.  length of input PDB != length of contig string: 222 != 232

Error executing job with overrides: ['inference.output_prefix=/home/lily/amelie/Workspace/RFdiffusion/outputs/partial_diffusion/run_20240812_063425/output_20240812_063425', 'inference.model_directory_path=/home/lily/amelie/Workspace/RFdiffusion/models', 'inference.input_pdb=/home/lily/amelie/Workspace/filtered_output/run_20240812_063425/round1/short_prefix_1_unrelaxed_rank_001_alphafold2_multimer_v3_model_3_seed_000.pdb', 'contigmap.contigs=[222-222/0 10]', 'diffuser.partial_T=1', 'contigmap.provide_seq=[172-205]']
```

## Question
I'm having trouble understanding how contigs work and how to specify them correctly. The error message suggests that there's a mismatch between the length of my input PDB (222) and the length implied by the contig string (232). 

1. Can someone explain how contigs work in RFDiffusion, particularly for partial diffusion?
2. How should I interpret and modify the contig string `[222-222/0 10]` to match my input PDB?
3. What's the relationship between `contigmap.contigs` and `contigmap.provide_seq`?

Any insights or documentation on how to properly set up contigs for partial diffusion would be greatly appreciated.
TYSM!!

**Comment by mavericb** [comment]
## Additional Information

As additional context, we previously used RFDiffusion for binder design with the following settings:

```yaml

# RFDiffusion settings

rfdiffusion:

  models_dir: "/home/lily/amelie/Workspace/RFdiffusion/models"

  inputs_dir: "/home/lily/amelie/Workspace/RFdiffusion/inputs"

  outputs_dir: "/home/lily/amelie/Workspace/RFdiffusion/outputs"

  num_designs: 2

  contigs: "H2-9/H11-30/H35-59/H62-72/H74-141/H149-228/0 10"

  hotspot_res: "H79,H83,H91"

  noise_scale_ca: 0.1

  noise_scale_frame: 0.1

```
